### ISSUE TITLE
Anonymize IP Adress

### ISSUE THREAD

**Issue by x4all** [jehna/ga-lite#10]
Add a function to anonymize ip adress. Guess should be something like

```
ga('create', 'UA-XXXXXXX-X', 'website.de');
ga('set', 'anonymizeIp', true);
ga('send', 'pageview');
```

**Comment by jehna** [comment]
This can be achieved with the [aip parameter](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#aip).

**Comment by jehna** [comment]
galite equvalent code syntax could be:
```
var galite = galite || {};
galite.UA = 'UA-XXXXXX'; // Insert your tracking code here
galite. anonymizeIp = true;
```

**Comment by x4all** [comment]
"_could be_" means that it is possible to realize it this way, or is it already done so that webmaster can already use it now?

**Comment by jehna** [comment]
@x4all meaning whoever writes the pull request to implement this feature should use the following syntax as a reference. So no, unfortunately this is not yet implemented.

**Comment by jehna** [comment]
@x4all this feature is now implemented and should be propagated shortly to the [jsdelivr CDN](https://www.jsdelivr.com/projects/ga-lite)
