### ISSUE TITLE
Improve compression of the minified version

### ISSUE THREAD

**Issue by tomasz1986** [jehna/ga-lite#13]
If you process the current minified version through [Closure Compiler](https://closure-compiler.appspot.com) and then [Ajax Minifier](http://sundgaard.dk/javascript-minify.aspx) the file size is further reduced from 1,111 bytes to 1,033 bytes.

As far as I understand, there are no side effects of the process.

Is there any reason not to use these compression methods for ga-lite?

**Comment by jehna** [comment]
The development environment is currently built on top of Grunt, so the minifying should also be done with Grunt.

At least the Closure Com

**Comment by jehna** [comment]
Seems that using the Closure Compiler with Advanced mode packs the code to 1020 bytes, which is a ~8% improvement.

**Comment by tomasz1986** [comment]
The advanced mode is usually buggy... Have you checked if the script still works?

Until now everything I have processed through Closure Compiler with Advanced mode turned out broken.

**Comment by jehna** [comment]
Did't test it yet

**Comment by jehna** [comment]
Tested closure compiler (finally).

The advanced optimizations gave too strong optimizations (the public `galite.UA` and `galite.anonymizeIp` were changed to one-char variables.

The `SIMPLE_OPTIMIZATIONS` seemed to give pretty good results. It managed to get rid of a few excess `var` declarations that saved a few bytes here and there.
