### ISSUE TITLE
Use CDN

### ISSUE THREAD

**Issue by jehna** [jehna/ga-lite#3]
This project should be added to a CDN, like https://github.com/cdnjs/cdnjs

**Comment by jehna** [comment]
Added to [jsdelivr](https://github.com/jsdelivr/jsdelivr) CDN, should add auto-update

**Comment by jehna** [comment]
Documentation: https://github.com/jsdelivr/libgrabber#add-updatejson-schema

**Comment by benniemosher** [comment]
@jehna Is this still pending the auto-update feature for jsdelivr CDN? Or is that completed now?

**Comment by jehna** [comment]
Still pending, I'm currently digging into it.

**Comment by benniemosher** [comment]
Anything that I can do to help get it taken care of?

--


Bennie Mosher / Problem Solver
bennie@racecar.email / +1 (970) 590-2040
Racecar Studio / A digital pit crew you can count on!
http://racecarstudio.com

**Comment by jehna** [comment]
Added [autoupdate to jsdelivr](https://github.com/jsdelivr/jsdelivr/pull/8700), the CDN should now update automatically.

@benniemosher this specific issue should now be tackled (just waiting for the autoupdate bot)

**Comment by benniemosher** [comment]
@jehna Nice work! Any other updates I can assist with?

**Comment by jehna** [comment]
@benniemosher if you're familiar with tools that help automated builds (like Rultor), there's issue #6. Other than that, you can just see what's missing from the implementation by looking at [the API documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters) and have fun implementing missing features.

**Comment by jehna** [comment]
Since [the latest version got pulled to jsdelivr](https://github.com/jsdelivr/jsdelivr/pull/8701), closing this issue for now.
