### ISSUE TITLE
Error from https://www.google-analytics.com/collect?

### ISSUE THREAD

**Issue by hazenet** [jehna/ga-lite#32]
Using ga-lite, and testing my site from tools.pingdom.com results in a error for the following URL:

https://www.google-analytics.com/collect?cid=0.048981909872964025.0.08325717668049037&v=1&tid=UA-48546849-2&dl=https%3A%2F%2Fhazenet.dk%2F&ul=en-us&de=UTF-8&dt=Hazenet.dk%20–%20VMware%20vSphere%2C%20vRealize%2C%20Scripting%20and%20more&sd=24-bit&sr=1024x1280&vp=1280x1024&dr=&t=pageview&z=1502283916933

![screen shot 2017-08-09 at 15 09 33](https://user-images.githubusercontent.com/1302109/29123084-cfc5b440-7d14-11e7-9aed-5e6f75462595.jpg)

Any explanation for this?
Is it something on my site or is it something in the ga-lite code?

**Comment by jehna** [comment]
Seems that some of the url parameters can now be malformed

**Comment by jehna** [comment]
This should be fixed in the version 2.0, as the whole url building logic was built from scratch.

Closing this issue since 2.0 has been released, please open a new one if you find any issues with the new implementation.
