### ISSUE TITLE
[FEATURE] allow user to send own custom events (make eventBuilder public)

### ISSUE THREAD

**Issue by AndreasA** [jehna/ga-lite#34]
It would be nice if one could send own custom events, e.g. on button click etc.
From what I see that should be possible by making the eventBuilder publicly available?

**Comment by AndreasA** [comment]
I am not completely sure but I think this might already be possible with v2?

**Comment by jehna** [comment]
Yep, version 2.0 includes a public API that is similar to the current official `analytics.js` API. You can see the progress on 2.0 from [the project's board](https://github.com/jehna/ga-lite/projects/1)

**Comment by jehna** [comment]
Closing this as a duplicate for #7

**Comment by AndreasA** [comment]
Ah. I didn't know that #7 was also asking regarding this. Thanks for the information and your work on this.
