### ISSUE TITLE
2.0 is not backwards-compatible with 1.x

### ISSUE THREAD

**Issue by jehna** [jehna/ga-lite#36]
The 1.x version is currently in use with 43M hits/month from jsDelivr. This provides us with an issue, since the old jsDelivr link did have the `latest` tag as default – so upgrading to 2.0 version would brake thousands of analytics on websites.

**Comment by jehna** [comment]
Possible fixes:

1. **Create code that replicates the 1.x API to the 2.0 version.**
   This way we can show a deprecation errors in the website (if someone monitors them) and gracefully remove the 1.x API at some later point
2. **We can create a new repository for 2.x**
   This would be better, as we could have a link from the current Gtihub page to the 2.0 version repository (like [UglifyJS project](https://github.com/mishoo/UglifyJS)), and let the users upgrade at some point if they feel the need to do so. This would also make sure the old websites never break.

**Comment by SimonCropp** [comment]
i would have assumed most people are using cdnjs https://cdnjs.com/libraries/ga-lite. so breaking APIs should only effect them when they explicitly upgrade

**Comment by SimonCropp** [comment]
but using latest  on jsDelivr people should expect the occasional api breaks and handle those. ie this is not your problem

**Comment by jimaek** [comment]
I believe you are safe in this case. Because your current /latest/ problem applies to our old URL format that is not getting updated anymore.
The new version you are going to release will be available only on the new /npm/ endpoint. 
So the damage should be non-existent or very limited.

**Comment by MartinKolarik** [comment]
>but using latest on jsDelivr people should expect the occasional api breaks and handle those. ie this is not your problem

That depends - the `latest` link was previously in the README as the recommended way and most people are just going to copy the link you put in the docs, so it is partially a responsibility of projects authors too.

However, as @jimaek correctly pointed out, the old link won't get new versions anymore, which solves your problem in this case.

**Comment by jehna** [comment]
Alright, thank you for your updates. Closing this issue, as the old URL will not be affected.
