### ISSUE TITLE
Implement custom dimensions

### ISSUE THREAD

**Issue by jehna** [jehna/ga-lite#38]
Custom dimensions might not work properly in version 2 yet.

https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

**Comment by carlmjohnson** [comment]
If I made a PR for custom dimensions, would the be interest in merging it? I'm considering using ga-lite for a work site, but I don't want to have to give up custom dimensions if I do.

**Comment by carlmjohnson** [comment]
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cd_ makes it seem like we'd just need to add cd1, cd2…, and cm1, cm2… to the FIELDS_TO_PARAMS_MAP object to get basic support.

**Comment by jehna** [comment]
> If I made a PR for custom dimensions, would the be interest in merging it?

I'd love to!

I'm on holidays for a week so I should have some time to check the code atm :)

If you're comfortable with doing unit tests, please add a few tests for the new functionality too.

**Comment by jehna** [comment]
And you can check https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#dimension for reference how the input should look like to match the original analytics.js

**Comment by carlmjohnson** [comment]
@jehna, did you get a chance to take a look at #83?

**Comment by jehna** [comment]
Ok, custom dimensions should be available at verison 2.1.0, which is [now live at npm](https://www.npmjs.com/package/ga-lite) 🎉

**Comment by carlmjohnson** [comment]
Awesome! Thanks for working on your vacation.
