### ISSUE TITLE
Illegal Invocation error due to lack of navigator.sendBeacon binding

### ISSUE THREAD

**Issue by brandoncarl** [jehna/ga-lite#380]
Hello – in certain cases navigator.sendBeacon fails to bind correctly causing an Illegal Invocation error in ga-lite. This can cause hundreds of errors per day:

![image](https://user-images.githubusercontent.com/5427971/142411010-e67afd0d-f582-43a9-9897-e8235724dd75.png)

The phenomenon is not specific to ga-lite and is documented here:
https://xgwang.me/posts/you-may-not-know-beacon/

vercel.js encountered the same issue here:
https://github.com/vercel/next.js/issues/23856

And addressed it here:
https://github.com/vercel/next.js/pull/26601/files

I believe the fix should be straightforward (binding sendBeacon to navigator).

Thanks for the great work.

**Comment by jehna** [comment]
Great, thank you for reporting high quality issue! 🙏
