### ISSUE TITLE
Multiple tracking codes?

### ISSUE THREAD

**Issue by janiosarmento** [jehna/ga-lite#48]
Please, how do I enable multiple tracking codes with GA-Lite?

Thanks!

**Comment by frank6tg** [comment]
I can't understand why you'd want to... I suppose you could use script twice but sites are unique.

**Comment by jehna** [comment]
Multiple tracking codes are fully supported by ga-lite, and it's common to use them.

You can use multiple tracking codes just like you would do in normal analytics.js, just follow the README's instructions about [migrating from analytics.js](https://github.com/jehna/ga-lite#migrating-from-analyticsjs).

More specifically:

> Replace any `ga()` function call with `galite()`

So in your case this code:

```
ga('create','UA-xxxxxx-1','auto');
ga('send','pageview');
ga('create','UA-xxxxxx-2','auto','fdola');
ga('fdola.send','pageview');
```

translates to ga-lite by replacing all `ga()` calls with `galite()` calls:

```
galite('create','UA-xxxxxx-1','auto');
galite('send','pageview');
galite('create','UA-xxxxxx-2','auto','fdola');
galite('fdola.send','pageview');
```

**Comment by jehna** [comment]
Closing this issue, let me know if you encounter any bugs using multiple tracking codes.
