### ISSUE TITLE
What exactly it's missing on this lib

### ISSUE THREAD

**Issue by kamov** [jehna/ga-lite#49]
Hi,

What exactly I don't get using this library instead of official?
I can see what I get, but not what I don't get.

Thanks!

**Comment by jehna** [comment]
Hey

This project is not yet feature-complete (although most of the basic features do work). You can find the list of known missing features from the [enhancement issues list](https://github.com/jehna/ga-lite/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement).

@kamov does this answer your question?

**Comment by kamov** [comment]
Yes thank you!
