### ISSUE TITLE
Still errors from https://www.google-analytics.com/collect? using v2

### ISSUE THREAD

**Issue by hazenet** [jehna/ga-lite#50]
Originally I had this error: https://github.com/jehna/ga-lite/issues/32
Now using v2 I am seeing this error instead:

https://www.google-analytics.com/collect?v=1&ul=en-us&de=UTF-8&dl=https%3A%2F%2Fhazenet.dk%2F&dt=Hazenet.dk%20–%20VMware%20vSphere%2C%20vRealize%2C%20Scripting%20and%20more&sd=24-bit&sr=1024x1280&vp=1280x1024&dr=&t=pageview&cid=0.5548558998852968.0.09024578682146966&tid=UA-48546849-2&z=1514110107125

![screen shot 2017-12-24 at 11 12 31](https://user-images.githubusercontent.com/1302109/34325748-69da0404-e89b-11e7-83c6-a49d8fd8a0f1.jpg)

So something is still wrong.

**Comment by jehna** [comment]
@hazenet are you sure you don't have any ad blockers on your browser? When I visit hazenet.dk, I don't get any errors and the call to Google Analytics API completes succesfully.

**Comment by jehna** [comment]
What is this tool that you're using? Pingdom website speed test?

**Comment by hazenet** [comment]
Yeah, the tool is https://tools.pingdom.com where I am testing "https://hazenet.dk" in.

**Comment by jehna** [comment]
It's possible that Google Analytics is blocking the Pingdom bot by default (which sounds reasonable), and that could result into 4xx response for the API request. Could this be the reason?

**Comment by hazenet** [comment]
Could be. I don't seem to get these errors (or I may not understand completely how to read the information) I my own browser developer view / web inspector / debugger.

**Comment by jehna** [comment]
Yep, I can confirm that there's no connection error present when I tested on real Firefox and Chrome on your site.

I checked that Pingdom is using a rather regular user-agent to check sites, so it can be that Google Analytics has just blocked their IP addresses.

**Comment by hazenet** [comment]
Okay, thanks for taking the time to test this.
Then the "problem" is purely cosmetic on the tools.pingdom.com website.
Please disregard this issue-thread then.
Merry Christmas

**Comment by jehna** [comment]
Merry christmas to you too :)
