### ISSUE TITLE
Hot to set session timeout?

### ISSUE THREAD

**Issue by 01Kuzma** [jehna/ga-lite#54]
Hi there!
Thank you for you module!
I'd like to know hot to set the session timeout with ES6?
Now I make it in such way:
```
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o)
                , m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-xxx-1', 'auto');
        ga('send', 'pageview');		
			setTimeout(function() {
			ga("send", "event", "New Visitor", location.pathname)
        }, 15000);     		
    </script>
```

**Comment by jehna** [comment]
Hey, can you describe in more detail what you're trying to achieve?

Session timeout (= after what time of inactivity the user's session is ended and next events count as a new session) is commonly set in the [Google Analytics' admin panel](https://analytics.google.com/analytics/web/#management/Settings/)

Here's a screenshot of the admin panel from [my personal blog's](thejunkland.com) analytics, where I have set the session timeout to 30 minutes:

<img width="708" alt="screen shot 2018-01-19 at 14 51 58" src="https://user-images.githubusercontent.com/2676795/35151814-70cea480-fd28-11e7-9087-7d13bbb65e8f.png">

**Comment by 01Kuzma** [comment]
Sorry, I've described it without proper details:
I mean the minimum time which user should remain on website in order to record it as session.
In my GA settings it's 15seconds:
```
        ga('send', 'pageview');		
			setTimeout(function() {
			ga("send", "event", "New Visitor", location.pathname)
        }, **15000**); 
```

**Comment by jehna** [comment]
Ah, I see!

You can use ga-lite exactly the same way in this case as you would in the official Google Analytics: Just replace the `ga` with `galite`:

```js
galite('create', 'UA-xxx-1', 'auto');
galite('send', 'pageview');		
  setTimeout(function() {
    galite("send", "event", "New Visitor", location.pathname)
}, 15000);   
```

**Comment by 01Kuzma** [comment]
Understood, thank you!
Just one problem left.
I'm using react and I've placed this code in index.js:
```
...
import galite from 'ga-lite';
class App extends React.Component {
  
  componentWillMount() {   
    
    galite('create', 'UA-105705654-1', 'auto');
    galite('send', 'pageview');		
    setTimeout(function() {
      galite("send", "event", "New Visitor", location.pathname)
    }, 
}
...
```

And google tag assistant throws me this error:
`No HTTP response detected`

Have I done something wrong?

**Comment by jehna** [comment]
Google Tag Assistant probably does not detect ga-lite, since ga-lite is not officially supported by Google (although the API endpoint ga-lite uses is).

You should see requests to www.google-analytics.com happening in your browser's developer tools' "Network" tab for each event/pageview that you send:

<img width="996" alt="screen shot 2018-01-19 at 15 52 17" src="https://user-images.githubusercontent.com/2676795/35153848-c0e39bbc-fd30-11e7-8cde-871e01001854.png">

**Comment by 01Kuzma** [comment]
My Js files are heavily compressed, that's what I see locally:
![image](https://user-images.githubusercontent.com/569504/35154393-c66f15d2-fd32-11e7-9957-d18fc448299e.png)
Is it ok?

While on live version I don't see something related to GA

**Comment by jehna** [comment]
If you see your session at Google analytics realtime, you can be 100% sure your code works and the events are firing fine. Good job! 👌

**Comment by jehna** [comment]
P.S. press "all" in your network tab and you'll see the Google analytics calls there too. Now it shows only the js files.

**Comment by 01Kuzma** [comment]
Thank you very much!
