### ISSUE TITLE
[RFC] Support for configuring a proxy.

### ISSUE THREAD

**Issue by zomars** [jehna/ga-lite#55]
As stated in [this article](https://medium.freecodecamp.org/save-your-analytics-from-content-blockers-7ee08c6ec7ee) is it posible to make this library to send all collect requests to a custom endpoint or proxy?

**Comment by jehna** [comment]
I probably don't need to tell that it's highly unethical for you to track your users/customers if they specifically have opted out of tracking with e.g. using an ad blocker?

Good! Now, with that aside it is very possible to do this with ga-lite.

There are two options to do this:

### 1. Override `_sendTo` method of the tracker

This can be done with the normal build of ga-lite. The tracker calls a method called `_sendTo` every time it wants to send an analytics event. You can easily change the URL there.

Here's an [example from the ga-lite's own test suite](https://github.com/jehna/ga-lite/blob/master/test/browser-tests/html/index.html#L15) that does exactly what you're trying to accomplish.

### 2. Build ga-lite yourself

You can clone this project, change the [base URL](https://github.com/jehna/ga-lite/blob/master/src/get-base-url.js#L4) to whatever you like, and build the source to your own version of ga-lite.

This allows you also to remove the [`doNotTrack` check](https://github.com/jehna/ga-lite/blob/master/src/ga-lite.js#L12) from the beginning of you want to maximize the amount of tracking done for your users.

**Comment by jehna** [comment]
I'll close this issue for now, let me know if you have any other issues :)
