### ISSUE TITLE
PageSpeed is still reporting leverage browser caching for analytics

### ISSUE THREAD

**Issue by anarchoi** [jehna/ga-lite#57]
I use latest ga-lite and PageSpeed is still reporting to leverage browser caching with analytics.js ... what am I doing wrong?
http://prntscr.com/it3mzj
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.defendanimals.com%2F&tab=desktop

**Comment by jehna** [comment]
You need to remove the original analytics.js

Check Google tag manager if that's the one that loads it

**Comment by anarchoi** [comment]
Thank you for the fast answer. After disabling Google Tag Manager the problem is fixed!

**Comment by jehna** [comment]
Great 🙂 Glad I could help!
