### ISSUE TITLE
Automatic version builds

### ISSUE THREAD

**Issue by jehna** [jehna/ga-lite#6]
Should include some kind of bot to automatically build the versions, like [Rultor](http://www.rultor.com/).

This is, so the correct versioning of the files would not be eligible for a human error

**Comment by jehna** [comment]
Related to the automatically updating CDN, see #3

**Comment by benniemosher** [comment]
Is this something that we could with a CI job that would happen after a tag was pushed and the tests pass?

**Comment by jehna** [comment]
@benniemosher I've seen a system where you can call a bot from the github's interface to do a successful tagging and building, like:

```
@bot publish version 1.5.0
```

So the bot would, at least, do the following tasks:
1. Change the version number in the `package.json`
2. Build grunt
3. Add files in `dist/`folder to git
4. Create and push a commit to master
5. Tag that new commit with new version number + push the version tag

**Comment by benniemosher** [comment]
Sounds like it should be simple enough to do via a small ruby script I would think.

--


Bennie Mosher / Problem Solver
bennie@racecar.email / +1 (970) 590-2040
Racecar Studio / A digital pit crew you can count on!
http://racecarstudio.com

**Comment by jehna** [comment]
Yes, that would also do. Or a simple bash script. Or even a grunt task.

**Comment by benniemosher** [comment]
Yeah, a grunt task would probably be best since we are running other grunt tasks in here. 

--


Bennie Mosher / Problem Solver
bennie@racecar.email / +1 (970) 590-2040
Racecar Studio / A digital pit crew you can count on!
http://racecarstudio.com

**Comment by jehna** [comment]
Created a bash script `do_release.sh` to create the build and used [travis](https://travis-ci.org/jehna/ga-lite/) to run the tests and publish to NPM
