### ISSUE TITLE
Embed Code and Call script

### ISSUE THREAD

**Issue by mahakala** [jehna/ga-lite#60]
src{https://cdnjs.cloudflare.com/ajax/libs/ga-lite/2.0.1/ga-lite.min.js}
window.galite=window.galite||function(){(galite.q=galite.q||[]).push(arguments)};
galite('create', 'xxxx', 'auto');
galite('send', 'pageview');
galite('set', 'anonymizeIp', true); 

I'm trying to embedding the script directly in html and then call it - but nothing seems to happen.
Did i miss something?

**Comment by jehna** [comment]
Hey @mahakala 

The script you pasted seems a bit odd. The correct script you should be using is:
```html
<script>
(function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
;c.parentNode.insertBefore(a,c)
})(window,document,"galite","script","https://cdn.jsdelivr.net/npm/ga-lite@2/dist/ga-lite.min.js");

galite('create', 'UA-XXXXXXXX-X', 'auto');
galite('send', 'pageview');
</script>
```

Make sure you replace the `UA-XXXXXXXX-X` with your own analytics code.

**Comment by jehna** [comment]
Do you have a live link with the script?

**Comment by frank6tg** [comment]
This is what I used (I put the JS file in my root folder meaning public_html then added this to the footer (you have to change the UA number). A side note I recommend using Google analytics tracking coe the normal way FIRST when you verify. THEn replace it. `<script>
(function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
;c.parentNode.insertBefore(a,c)
})(window,document,"galite","script","/ga-lite.min.js");

galite('create', 'UA-XXXXXXXX-X', 'auto');
galite('send', 'pageview');
</script>

<script>
window.addEventListener(
  'unload',
  function () { galite('send', 'timing', 'JS Dependencies', 'unload') }
)
</script>`

**Comment by mahakala** [comment]
21:54:35.592 console.log(navigator.doNotTrack)
21:54:35.551 1 debugger eval code:1:1
21:54:35.548 undefined
