### ISSUE TITLE
Yarn run build not working

### ISSUE THREAD

**Issue by sasirura** [jehna/ga-lite#627]
I cloned the repo and run yarn install. And then yarn run build. I got the following error

![Screenshot 2023-03-08 233931](https://user-images.githubusercontent.com/42542164/223795103-143a4876-5118-4778-99ed-5e3b82511d07.png)

**Comment by sasirura** [comment]
v16.17.1

**Comment by jehna** [comment]
Should be fixed now in `master` branch, thanks for reporting 👍

**Comment by sasiruLK** [comment]
Thank you ! it worked. you just removed the type in the package.json file right? can you explain or give me a link or something to understand about it ?
