### ISSUE TITLE
Features Available? ECommerce and Block Yourself from Analytics

### ISSUE THREAD

**Issue by nbexiga** [jehna/ga-lite#66]
Hi
just a great code to get better results in Page Insights.

Is it possible to add the option to track Ecommerce conversions ?  Because it is not getting any data from client purchases. 

I want to know if its possible too for the Google Addon "Block Yourself from analytics" to block the traffic from the addon , because i do many changes and test during the day in my store and it's always getting traffic from that location that i do the changes.

Many thanks ,
waiting your feedback

**Comment by jehna** [comment]
> Is it possible to add the option to track Ecommerce conversions ? Because it is not getting any data from client purchases.

Can you tell which code you're using to track your conversions?

> I want to know if its possible too for the Google Addon "Block Yourself from analytics" to block the traffic from the addon

You can [contact the creator of the Block Yourself plugin](http://www.igorware.com/contact) to get this fixed.

The easiest way to block the `ga-lite` is to [enable "do not track" setting in your browser](https://medium.com/upscribe/how-to-disable-enable-do-not-track-dnt-in-your-browser-db6b6bd7dd0a).

**Comment by nbexiga** [comment]
Hi @jehna 
So what could be wrong for not getting conversions and order from my store? :(
I am using  this code 


<script>// <![CDATA[
(function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
;c.parentNode.insertBefore(a,c)
})(window,document,"galite","script","https://cdn.jsdelivr.net/npm/ga-lite@2/dist/ga-lite.min.js");
galite('create', 'UA-XXXXX', 'auto');
galite('send', 'pageview');
galite('require', 'ecommerce');
// ]]></script>


I already sent some emails to the creator but no reply from him :(

How do i block the ga-lite from my browser?

**Comment by nbexiga** [comment]
Hi @jehna
So what could be wrong for not getting conversions and order from my store? :(
I am using this code

script
(function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
;c.parentNode.insertBefore(a,c)
})(window,document,"galite","script","https://cdn.jsdelivr.net/npm/ga-lite@2/dist/ga-lite.min.js");

galite('create', 'UA-XXXXXXX', 'auto');
galite('send', 'pageview');
galite('require', 'ecommerce');
/script

I already sent some emails to the creator but no reply from him :(

How do i block the ga-lite from my browser?

**Comment by jehna** [comment]
Seems that you're using the [plugin API](https://github.com/jehna/ga-lite/issues/39), which is not yet supported by ga-lite. It's on the roadmap, and you can subscribe to the issue #39 to keep yourself posted :)

> How do i block the ga-lite from my browser?

Like stated in the previous comment, turn on the "do not track" -setting on your browser. This blocks ga-lite from sending any analytics. Here are instructions to do it in all common browsers:

https://medium.com/upscribe/how-to-disable-enable-do-not-track-dnt-in-your-browser-db6b6bd7dd0a

**Comment by nbexiga** [comment]
OK, i will try to configure and add the uBlock  ;) thanks for the tip.

and thanks for the update on google analytics lag... i asked you because as i did changes i tought that was anything not working as expected.
many thanks
have a great weekend

**Comment by jehna** [comment]
Great weekend to you too :)
