### ISSUE TITLE
Are Conversion Tags Possible & Phone Number Tags

### ISSUE THREAD

**Issue by Dezzign** [jehna/ga-lite#72]
Hi,
Awesome project! Just noticing when trying to add the below conversion tags that it doesn't seem to work.

I know that you change 'gtag' to 'galite' in the below examples, but I just get errors in the console when trying to run these conversion tags.

Firstly AdWords ask you to add a tag like this if you already have analytics running (which I do as it's galite analytics).

But basically having no joy with the below set up as per the screenshot: 
https://www.screencast.com/t/lUPDs4xS

And the raw code here for reference:
`<script>
        (function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
        ;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
        ;c.parentNode.insertBefore(a,c)
        })(window,document,"galite","script","https://cdn.jsdelivr.net/npm/ga-lite@2/dist/ga-lite.min.js");

        galite('create', 'UA-XXXXXXXX-X', 'auto');
        galite('send', 'pageview');
        galite('config', 'AW-930415418');
        galite('config', 'AW-930415418/n5jDCMeornAQuobUuwM', {
            'phone_conversion_number': '02 9939 xxxx'
        });
    </script>`

Any ideas please?

Thanks.
Richard

**Comment by jehna** [comment]
Hey @Dezzign 

> I know that you change 'gtag' to 'galite'

I think you're trying to use this project to replace `gtag` (Google Tag Manager) instead of `ga` (Google Analytics). This project can be used as a drop-in replacement for Google Analytics, but not for Google Tag Manager.

**Comment by Dezzign** [comment]
Hi Jehna,

Thanks for the response. not quite trying to use it like a tag manager. The issue is that:

1) as AdWords states - If the global site tag is already installed on all pages, but comes from another Google product (such as Google Analytics) then I can just add the following snippet to count conversions as well:
gtag('config', 'AW-930415418');

2) And then add the phone number conversions script separately:
<script>
  gtag('config', 'AW-930415418/n5jDCMeornAQuobUuwM', {
    'phone_conversion_number': '02 9939 xxxx'
  });
</script>

Perhaps my mistake was thinking that the Galite analytics also has the 'global site tag' contained within it like the normal analytics code does? Does that make sense?

Thanks,
Richard

**Comment by jehna** [comment]
> Perhaps my mistake was thinking that the Galite analytics also has the 'global site tag' contained within it like the normal analytics code does? Does that make sense?

That's correct: Unfortunately ga-lite can not be used as anything else than sending analytics events from your website to Google Analytics.

Nowadays Google Analytics recommends to install itself through Google Tag Manager. The "global site tag" that's referred to is actually Google Tag Manager, which is a Google product that you can use to load arbitrary code (like Google Analytics) on your website.

Google Tag Manager uses a similar interface as Google Analytics (`something('config', value, ...)`), but those two are different products doing a bit different things.

**Comment by jehna** [comment]
Closing due inactivity, please open a new issue if I can help you with anything else :)
