### ISSUE TITLE
Disableing of ga-lite through cookie

### ISSUE THREAD

**Issue by dbieling** [jehna/ga-lite#73]
I have a privacy concern about the code-snippet. Even if it's following browsers tracking-choice, it is not enough for european websites, to use the code. 
According to the GDPR User has to get a choice, to manually disable Tracking. 
I used GA-Lite within a website, and discovered, that the opt-out-plugin does not work. 

Can anybody help, how to change the opt-out-cookie-code, that it will work with GDPR and go-lite? Thanks!
  
```
// Set to the same value as the web property used on the site
var gaProperty = 'UA-XXXXXXX-X';
	
// Disable tracking if the opt-out cookie exists.
var disableStr = 'ga-disable-' + gaProperty;
if (document.cookie.indexOf(disableStr + '=true') > -1) {
  window[disableStr] = true;
}
// Opt-out function for Google Analytics 
function gaOptout() {
  document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window[disableStr] = true;
}
</script>
```

**Comment by jehna** [comment]
Hey @dbieling, great point! Opt-out via cookie is not yet implemented in ga-lite, but I can make it a priority to do so.

Is the code sample you provided a working script that disables normal Google Analytics? I'd like to see ga-lite being disabled with the same cookie as the normal google analytics, as that would ensure compatibility with exsiting opt-out scripts

**Comment by dbieling** [comment]
Thanks for your awesome answer. I am really glad, that this thought is considered for this project. I will be very glad, to switch to galite again. I am writing here my full configuration, to be sure, that nothing is overlooked. 
This configuration worked with the created google deactivation button!

// Google deactivation Button within the Site:
<a id="gaOptout" href="javascript:gaOptout();" class="et_pb_button et_pb_button_0 et_pb_bg_layout_light db_pb_button_1" onclick="alert('Google Analytics wurde deaktiviert');">Google Analytics deaktivieren</a>

// Code added to the `<body>`
<script async type="text/javascript"> 
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-123456200-1');
	
// <![CDATA[
// Google Analytics - deactivation cookie
// Set to the same value as the web property used on the site
var gaProperty = 'UA-123456200-1';
	
// Disable tracking if the opt-out cookie exists.
var disableStr = 'ga-disable-' + gaProperty;
if (document.cookie.indexOf(disableStr + '=true') > -1) {
  window[disableStr] = true;
}
// Opt-out function for Google Analytics 
function gaOptout() {
  document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
  window[disableStr] = true;
}
</script>

After that script, I added the following code snippet: 
</script>


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123456200-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', UA-123456200-1, { 'anonymize_ip': true });

</script>

**Comment by jehna** [comment]
As a reference: Here's Google's side of that feature:
https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out#opt-out_of_tracking_for_your_site

**Comment by jehna** [comment]
Ok, this feature is now implemented, and it will be soon rolled out, probably in version 2.0.4
