### ISSUE TITLE
It should be mentioned that ga-lite doesn't use cookies

### ISSUE THREAD

**Issue by haggen** [jehna/ga-lite#79]
Since it advertises compliance with `analytics.js` it should be mentioned somewhere in the docs that `ga-lite` skip cookie usage entirely and relies on local storage.

Perhaps also worth mentioning is that differently from [what Google says on their docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage#analyticsjs) it only sets a single key/value--the user id.

I looked it up because I needed to implement a storage consent prompt on my client's site, which is using `ga-lite`.

If it sounds like a legitimate request I'd be glad to submit a PR.

**Comment by jehna** [comment]
Good point! This should be documented on the readme.md level.

**Comment by jehna** [comment]
A pull request would be greatly appreciated!

**Comment by jehna** [comment]
Closed via #80
