### ISSUE TITLE
Stop working on Chrome 85+ for somehow

### ISSUE THREAD

**Issue by tdtgit** [jehna/ga-lite#87]
**Issues**
- No event send to Analytics
- No error throwed
- Both direct include to HTML or Webpack build.

I've done a test on Safari (MacOS) and it's still work fine.

**Comment by jehna** [comment]
This sounds really alarming! I'll check this out when I get to my computer, but meanwhile I appreciate if there's any other debugging you can do.

For example there are some browser-based tests in the repository that you could try to run to check if they work with your browser.

**Comment by tdtgit** [comment]
Doing a `yarn test` with all passeds, Chrome Canary are fine also. I'm uninstall my Chrome to see how.

**Comment by jehna** [comment]
I'm guessing there's some browser plugin or setting that's blocking the requests. 

What's the value if you type `navigator.doNotTrack` to your browser's console? (you can also check your browser's settings)
Enabling the "do not track" setting effectively disables ga-lite. Some browser plugins might prevent ga-lite from working too.

**Comment by tdtgit** [comment]
Your guess are correct. Turn off **Do Not Track** helped.

My tests on `navigator.doNotTrack`:
- Safari on Catalina: `undefined`, ga-lite is working
- Chrome Canary: `null`, ga-lite is working
- Chrome mainline: `"1"`, ga-lite is not working

**Comment by jehna** [comment]
Nice! So ga-lite seems to be working as expected, honoring your browser's preferences.

If nothing's changed, Google still has the "do not track" disabled by default, so most people probably have their setting disabled. If you have set the "do not track" setting on at some point on your main chrome, it might remember the setting on user preferences or when you log in with your Google account even if you reinstall the browser.

At least a quick Google search did not indicate that Google wolud have changed their default settings in the last few months.

If you want to have ga-lite working for your chrome mainline browser, please consider turning the "no not track" setting off.

I'll close this issue for now, please feel free to re-open it if there's anything I've missed or if the problem still persists.

**Comment by haggen** [comment]
Hi! Might I suggest adding something like a `console.info` notifying the developer/user that GA Lite is honoring their Do Not Track preference? Cause right now the experience is just really confusing. I didn't recall turning it on, and since this feature has been largely ignored by tech and users alike I completely forgot about it. Thanks in advance.
